# Generated by Django 3.1.7 on 2021-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productflavor',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
