# Generated by Django 3.1.7 on 2021-03-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productflavor_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productflavor',
            old_name='stock',
            new_name='stock_flavor',
        ),
    ]
