# Generated by Django 3.1.7 on 2021-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210306_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productflavor',
            name='stock_flavor',
        ),
        migrations.AddField(
            model_name='productflavor',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
