# Generated by Django 3.1.7 on 2021-03-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_flavor_productflavor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productflavor',
            unique_together={('product', 'flavor')},
        ),
    ]
