# Generated by Django 3.1.7 on 2021-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210320_1820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
