# Generated by Django 3.1.7 on 2021-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210320_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='flavor',
            field=models.CharField(default='Vanille', max_length=100),
        ),
    ]
