# Generated by Django 3.1.7 on 2021-03-29 13:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orderproduct_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
